```{r}
rm(list=ls())

knitr::opts_chunk$set(echo = FALSE)

library(lme4)
library(lmerTest)

pathToFolder <- '/Users/dbao/Library/CloudStorage/GoogleDrive-sherrydbao@gmail.com/My Drive/road_construction_data/data/2022_online/'
save_folder <- file.path(pathToFolder, 'stat_model/final/')
data_folder <- file.path(pathToFolder, 'R_analysis_data')

data <- read.csv(file.path(data_folder, "dk_stats.csv"))
data["firstmoveRT_log"] = log(data["firstmoveRT"]+1)
```

# eq:stats_RT_condition
```{r}
model = lmerTest::lmer(firstmoveRT_log ~ condition_UA + (1|subject) + (1|puzzle), data=data)
model_full = lmerTest::lmer(firstmoveRT_log ~ condition_UA + (1+condition_UA|subject) + (1+condition_UA|puzzle), data=data)
summary(model)
summary(model_full)

confint(model, method = "Wald", level = 0.95, parm = "beta_")
confint(model_full, method = "Wald", level = 0.95, parm = "beta_")
```

# eq:stats_delta_cum_error_sequence
```{r}
data <- read.csv(file.path(data_folder, "do_redo_comparison.csv"))
head(data)
```

```{r}
data$subject <- as.factor(data$subject)
data$puzzleID <- as.factor(data$puzzleID)
data$do_redo <- as.factor(data$do_redo)

model = lme4::glmer(error_seq ~  do_redo + (1 |subject) + (1 |puzzleID), data = data, family = "poisson")
model_full = lme4::glmer(error_seq ~  do_redo + (1|subject) + ( 1|puzzleID), data = data, family = "poisson")

summary(model)
ci = confint(model, method = "Wald", level = 0.95, parm = "beta_")
ci
exp(ci)   # gives OR scale
exp(coef(summary(model))[, "Estimate"])  # point estimate ORs

```


```{r}

model = lme4::glmer(error_move ~  do_redo + (1 |subject) + (1 |puzzleID), data = data, family = "poisson")
model_full = lme4::glmer(error_move ~  do_redo + (1  |subject) + (1  |puzzleID), data = data, family = "poisson")

summary(model)
summary(model_full)
ci = confint(model, method = "Wald", level = 0.95, parm = "beta_")
ci
exp(ci)   # gives OR scale
exp(coef(summary(model))[, "Estimate"])  # point estimate ORs
```

# optimal submissions
```{r}
data_puzzle <- read.csv(file.path(data_folder, "data_new.csv"))

data_puzzle$subject <- as.factor(data_puzzle$subject)
data_puzzle$puzzle <- as.factor(data_puzzle$puzzle)
data_puzzle$zero_missed_reward <- as.integer(data_puzzle$final_missed_reward == 0)

model = lme4::glmer(zero_missed_reward ~ condition + (1+condition|subject) + (1+condition|puzzle), 
                    data = data_puzzle, family = binomial(link = "logit"))
summary(model)
ci = confint(model, method = "Wald", level = 0.95, parm = "beta_")
ci
exp(ci)   # gives OR scale
exp(coef(summary(model))[, "Estimate"])  # point estimate ORs

model_klein = lme4::glmer(zero_missed_reward ~ condition + (1|subject) + (1|puzzle), 
                    data = data_puzzle, family = binomial(link = "logit"))
summary(model_klein)
ci = confint(model_klein, method = "Wald", level = 0.95, parm = "beta_")
ci
exp(ci)   # gives OR scale
exp(coef(summary(model))[, "Estimate"])  # point estimate ORs
```
```{r}
model = lme4::glmer(zero_missed_reward ~ condition + mas + ( 1|subject) + (1 |puzzle), 
                    data = data_puzzle, family = binomial(link = "logit"),control = glmerControl(optimizer = "bobyqa",
                                      optCtrl = list(maxfun = 1e5)))
summary(model)
```

