```{r}
rm(list=ls())

knitr::opts_chunk$set(echo = FALSE)

library(lme4)
library(lmerTest)

pathToFolder <- '/Users/dbao/Library/CloudStorage/GoogleDrive-sherrydbao@gmail.com/.shortcut-targets-by-id/1sYZNVBbYCrHcHjo-9xdKcA4wLnob9ZEq/road_construction/data/2022_online/'
save_folder <- file.path(pathToFolder, 'stat_model/final/')
data_folder <- file.path(pathToFolder, 'R_analysis_data')

data <- read.csv(file.path(data_folder, "dk_stats.csv"))
data["firstmoveRT_log"] = log(data["firstmoveRT"]+1)
```

```{r}
model = lmerTest::lmer(firstmoveRT_log ~ condition_UA + (1|subject) + (1|puzzle), data=data)

summary(model)
```

```{r}
data <- read.csv(file.path(data_folder, "do_redo_comparison.csv"))
head(data)
```

```{r}
data$subject <- as.factor(data$subject)
data$puzzleID <- as.factor(data$puzzleID)
data$do_redo <- as.factor(data$do_redo)

model = lme4::glmer(error_seq ~  do_redo + (1 |subject) + (1 |puzzleID), data = data, family = "poisson")

summary(model)

model = lme4::glmer(error_move ~  do_redo + (1 |subject) + (1 |puzzleID), data = data, family = "poisson")

summary(model)
```

